### ISSUE TITLE
local variable completion is invalid

### ISSUE THREAD

**Issue by luixiao1223** [ptrv/company-lua#8]
After add the company-lua. Then the default function of company is invalid.If I define a local variable "mytable" then type "my" string cannot get any completion candidates.

**Comment by ptrv** [comment]
`compant-lua` only completes keywords from the standard library. You will not get completion for `mytable`. You will need a combination of backends.

 How did you add the `company-lua` backend?

What is the output of `company-diag`?

I think instead of adding the completer as in the readme you should combine multiple backends to get completion from them at the same time:

```emacs-lisp
(defun my-lua-mode-company-init ()
  (setq-local company-backends '((company-lua
                                  company-etags
                                  company-dabbrev-code
                                  company-yasnippet))))
(add-hook 'lua-mode-hook #'my-lua-mode-company-init)
```

**Comment by luixiao1223** [comment]
Thx,The problem is solved!

My setting is 
(add-to-list 'company-backends 'company-lua)
It works again When I change this to 
(defun my-lua-mode-company-init ()
  (setq-local company-backends '((company-lua
                                  company-etags
                                  company-dabbrev-code
                                  company-yasnippet))))
(add-hook 'lua-mode-hook #'my-lua-mode-company-init)
